---
language: objective-c
cache: cocoapods
sudo: false
osx_image: xcode7

before_install:
 - gem install activesupport
 - gem install cocoapods xcpretty
 - pod setup >/dev/null

script:
 - xcodebuild -workspace Santa.xcworkspace -scheme All -derivedDataPath build build test CODE_SIGN_IDENTITY='' | xcpretty -sc && exit ${PIPESTATUS[0]}
